// src/routes/communities/+page.svelte
<script lang="ts">
	import { Loader2 } from '@lucide/svelte';
	import { list_communities } from '$lib/data';
	import Avatar from '$components/Avatar.svelte';

	let communities = $state<Awaited<ReturnType<typeof list_communities>>>([]);
	let loading = $state(true);

	$effect(() => {
		list_communities()
			.then((d) => (communities = d))
			.finally(() => (loading = false));
	});
</script>

{#if loading}
	<div class="flex h-[calc(100vh-3.5rem)] items-center justify-center">
		<Loader2 class="h-8 w-8 animate-spin" />
	</div>
{:else}
	<div class="container mx-auto p-4 sm:p-6">
		<h1 class="mb-6 text-3xl font-bold">communities</h1>
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each communities as c (c.name)}
				<a href="/c/{c.name}" class="card block h-full p-4 hover:shadow-lg">
					<div class="mb-2 flex items-center space-x-4">
						<Avatar src={c.avatar_url} name={c.display_name} class="h-12 w-12" />
						<div>
							<h2 class="text-lg font-semibold">{c.display_name}</h2>
							<p class="text-sm text-muted-foreground">{c.member_count || 0} members</p>
						</div>
					</div>
					<p class="line-clamp-2 text-sm text-muted-foreground">{c.description}</p>
				</a>
			{/each}
		</div>
	</div>
{/if}

// src/pages/Communities.tsx

import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Link } from 'react-router-dom';
import { Card } from '@/components/ui/card';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Loader2 } from 'lucide-react';

const CommunitiesPage = () => {
  const { data: communities, isLoading } = useQuery({
    queryKey: ['communities'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('communities')
        .select('name, display_name, description, avatar_url, member_count');
      
      if (error) throw error;
      return data;
    }
  });

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-[calc(100vh-theme(space.14))]">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 sm:p-6">
      <h1 className="text-3xl font-bold mb-6">Communities</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {communities?.map(community => (
          <Link to={`/c/${community.name}`} key={community.name} className="block">
            <Card className="p-4 hover:shadow-lg transition-shadow h-full">
              <div className="flex items-center space-x-4 mb-2">
                <Avatar className="h-12 w-12">
                  <AvatarImage src={community.avatar_url || undefined} />
                  <AvatarFallback>{community.display_name.charAt(0)}</AvatarFallback>
                </Avatar>
                <div>
                  <h2 className="text-lg font-semibold">{community.display_name}</h2>
                  <p className="text-sm text-muted-foreground">{community.member_count || 0} members</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground line-clamp-2">{community.description}</p>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default CommunitiesPage;
