// src/components/AddAnimationModal.svelte
<script lang="ts">
	import { Plus, Upload } from '@lucide/svelte';
	import { auth } from '$lib/auth.svelte';
	import { toast } from '$lib/toast.svelte';
	import { create_animation, create_community } from '$lib/data';
	import { thumb_from_video, upload } from '$lib/upload';
	import CommunityCombobox from './CommunityCombobox.svelte';
	import FileUploadSection from './FileUploadSection.svelte';

	const a = auth();
	let open = $state(false);
	let title = $state('');
	let description = $state('');
	let video = $state<File | null>(null);
	let thumb = $state<File | null>(null);
	let community_id = $state('');
	let new_name = $state('');
	let busy = $state(false);

	function reset() {
		title = '';
		description = '';
		video = null;
		thumb = null;
		community_id = '';
		new_name = '';
	}

	async function submit(e: Event) {
		e.preventDefault();
		if (!a.user) return toast('error', 'you must be logged in to upload animations', 'err');
		if (!title.trim()) return toast('error', 'title is required', 'err');
		if (!video) return toast('error', 'please select a video file', 'err');
		if (video.size > 50 * 1024 * 1024) return toast('error', 'video file size must be less than 50mb', 'err');
		if (thumb && thumb.size > 5 * 1024 * 1024) return toast('error', 'image file size must be less than 5mb', 'err');
		if (community_id === 'create-new' && !new_name.trim()) return toast('error', 'please enter a community name', 'err');
		busy = true;
		try {
			let cid: string | null = community_id === 'none' || !community_id ? null : community_id;
			if (community_id === 'create-new') cid = await create_community(new_name.trim());
			const video_url = await upload(video);
			let thumbnail_url: string | null = thumb ? await upload(thumb) : null;
			if (!thumbnail_url) {
				try {
					thumbnail_url = await upload(await thumb_from_video(video));
				} catch {
					/* optional */
				}
			}
			await create_animation({
				title: title.trim(),
				description: description.trim() || null,
				video_url,
				thumbnail_url,
				community_id: cid
			});
			toast('animation uploaded successfully!');
			open = false;
			reset();
		} catch {
			toast('error', 'failed to upload animation', 'err');
		} finally {
			busy = false;
		}
	}
</script>

{#if a.user}
	<button class="btn" type="button" onclick={() => (open = true)}>
		<Plus class="mr-2 h-4 w-4" /> add animation
	</button>
	{#if open}
		<div class="overlay" onclick={() => !busy && (open = false)} onkeydown={(e) => e.key === 'Escape' && !busy && (open = false)} role="presentation">
			<div class="modal max-h-[90vh] max-w-[600px] overflow-y-auto" tabindex="-1" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()} role="dialog" aria-modal="true">
				<h2 class="text-lg font-semibold">upload new animation</h2>
				<p class="mb-4 text-sm text-muted-foreground">share your animation with the community</p>
				<form onsubmit={submit} class="space-y-6">
					<div class="space-y-2">
						<label class="text-sm font-medium" for="title">title *</label>
						<input id="title" class="field" bind:value={title} placeholder="enter animation title" required disabled={busy} />
					</div>
					<div class="space-y-2">
						<label class="text-sm font-medium" for="desc">description</label>
						<textarea id="desc" class="area" rows="3" bind:value={description} placeholder="describe your animation..." disabled={busy}></textarea>
					</div>
					<FileUploadSection bind:video bind:thumb disabled={busy} />
					<div class="space-y-2">
						<span class="text-sm font-medium">community (optional)</span>
						<CommunityCombobox bind:value={community_id} disabled={busy} />
					</div>
					{#if community_id === 'create-new'}
						<div class="space-y-2">
							<label class="text-sm font-medium" for="newc">new community name *</label>
							<input id="newc" class="field" bind:value={new_name} placeholder="enter community name" disabled={busy} />
						</div>
					{/if}
					<div class="flex justify-end space-x-3">
						<button class="btn-outline" type="button" onclick={() => (open = false)} disabled={busy}>cancel</button>
						<button class="btn" type="submit" disabled={busy}>
							<Upload class="mr-2 h-4 w-4" />
							{busy ? 'uploading...' : 'upload animation'}
						</button>
					</div>
				</form>
			</div>
		</div>
	{/if}
{/if}

// src/components/AddAnimationModal.tsx

import React, { useState } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Plus, Upload } from 'lucide-react'
import { CommunityCombobox } from './CommunityCombobox'
import { FileUploadSection } from './FileUploadSection'
import { useAnimationUpload } from '@/hooks/useAnimationUpload'

export const AddAnimationModal = () => {
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [videoFile, setVideoFile] = useState<File | null>(null)
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null)
  const [communityId, setCommunityId] = useState<string>('')
  const [newCommunityName, setNewCommunityName] = useState('')
  const { user } = useAuth()
  const { createAnimationMutation, isUploading } = useAnimationUpload()

  const resetForm = () => {
    setTitle('')
    setDescription('')
    setVideoFile(null)
    setThumbnailFile(null)
    setCommunityId('')
    setNewCommunityName('')
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!user) {
      toast.error('You must be logged in to upload animations')
      return
    }

    if (!title.trim()) {
      toast.error('Title is required')
      return
    }

    if (!videoFile) {
      toast.error('Please select a video file')
      return
    }

    if (communityId === 'create-new' && !newCommunityName.trim()) {
      toast.error('Please enter a community name')
      return
    }

    createAnimationMutation.mutate({
      title,
      description,
      videoFile,
      thumbnailFile,
      communityId,
      newCommunityName
    }, {
      onSuccess: () => {
        setOpen(false)
        resetForm()
      }
    })
  }

  const handleVideoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      if (!file.type.startsWith('video/')) {
        toast.error('Please select a valid video file')
        return
      }
      
      if (file.size > 50 * 1024 * 1024) {
        toast.error('Video file size must be less than 50MB')
        return
      }
      
      setVideoFile(file)
    }
  }

  const handleThumbnailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      if (!file.type.startsWith('image/')) {
        toast.error('Please select a valid image file')
        return
      }
      
      if (file.size > 5 * 1024 * 1024) {
        toast.error('Image file size must be less than 5MB')
        return
      }
      
      setThumbnailFile(file)
    }
  }

  const handleCommunityChange = (value: string) => {
    setCommunityId(value)
    if (value !== 'create-new') {
      setNewCommunityName('')
    }
  }

  if (!user) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          Add Animation
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Upload New Animation</DialogTitle>
          <DialogDescription>
            Share your animation with the community
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title">Title *</Label>
            <Input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Enter animation title"
              required
              disabled={isUploading}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Describe your animation..."
              rows={3}
              disabled={isUploading}
            />
          </div>

          <FileUploadSection
            videoFile={videoFile}
            thumbnailFile={thumbnailFile}
            onVideoChange={handleVideoChange}
            onThumbnailChange={handleThumbnailChange}
            onVideoRemove={() => setVideoFile(null)}
            onThumbnailRemove={() => setThumbnailFile(null)}
            disabled={isUploading}
          />

          <div className="space-y-2">
            <Label htmlFor="community">Community (Optional)</Label>
            <CommunityCombobox
              value={communityId}
              onValueChange={handleCommunityChange}
              disabled={isUploading}
            />
          </div>

          {communityId === 'create-new' && (
            <div className="space-y-2">
              <Label htmlFor="new-community-name">New Community Name *</Label>
              <Input
                id="new-community-name"
                value={newCommunityName}
                onChange={(e) => setNewCommunityName(e.target.value)}
                placeholder="Enter community name"
                disabled={isUploading}
              />
              <p className="text-xs text-muted-foreground">
                The community will be created and your animation will be added to it
              </p>
            </div>
          )}

          <div className="flex justify-end space-x-3">
            <Button 
              type="button" 
              variant="outline" 
              onClick={() => setOpen(false)}
              disabled={isUploading}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isUploading || createAnimationMutation.isPending}>
              <Upload className="h-4 w-4 mr-2" />
              {isUploading ? 'Uploading...' : 'Upload Animation'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
