// src/components/AddToPlaylistModal.tsx

import React, { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/integrations/supabase/client'
import { useAuth } from '@/contexts/AuthContext'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { toast } from '@/components/ui/use-toast'
import { Plus, Loader2 } from 'lucide-react'

interface AddToPlaylistModalProps {
  animationId: string
  animationTitle: string
}

export const AddToPlaylistModal = ({ animationId, animationTitle }: AddToPlaylistModalProps) => {
  const { user } = useAuth()
  const queryClient = useQueryClient()
  const [isOpen, setIsOpen] = useState(false)

  const { data: playlists, isLoading } = useQuery({
    queryKey: ['playlists', user?.id],
    queryFn: async () => {
      if (!user) return []
      const { data, error } = await supabase
        .from('playlists')
        .select('id, name, description')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })

      if (error) throw error
      return data
    },
    enabled: !!user && isOpen
  })

  const addToPlaylistMutation = useMutation({
    mutationFn: async (playlistId: string) => {
      if (!user) throw new Error('You must be logged in')
      
      const { error } = await supabase
        .from('playlist_items')
        .insert({
          playlist_id: playlistId,
          post_id: animationId
        })
      
      if (error) throw error
    },
    onSuccess: (_, playlistId) => {
      const playlist = playlists?.find(p => p.id === playlistId)
      toast({ 
        title: 'Added to playlist!', 
        description: `"${animationTitle}" was added to "${playlist?.name}"` 
      })
      queryClient.invalidateQueries({ queryKey: ['playlist-items', playlistId] })
      setIsOpen(false)
    },
    onError: (error: any) => {
      if (error.message?.includes('duplicate key value')) {
        toast({ 
          title: 'Already in playlist', 
          description: 'This animation is already in that playlist',
          variant: 'destructive'
        })
      } else {
        toast({ 
          title: 'Failed to add to playlist', 
          description: error.message,
          variant: 'destructive'
        })
      }
    }
  })

  if (!user) return null

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          <Plus className="h-4 w-4 mr-2" />
          Add to Playlist
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add to Playlist</DialogTitle>
          <DialogDescription>
            Choose a playlist to add "{animationTitle}" to
          </DialogDescription>
        </DialogHeader>
        
        {isLoading ? (
          <div className="flex justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin" />
          </div>
        ) : playlists && playlists.length > 0 ? (
          <div className="space-y-2 max-h-60 overflow-y-auto">
            {playlists.map((playlist) => (
              <Button
                key={playlist.id}
                variant="ghost"
                className="w-full justify-start h-auto p-4"
                onClick={() => addToPlaylistMutation.mutate(playlist.id)}
                disabled={addToPlaylistMutation.isPending}
              >
                <div className="text-left">
                  <div className="font-medium">{playlist.name}</div>
                  {playlist.description && (
                    <div className="text-sm text-muted-foreground line-clamp-2">
                      {playlist.description}
                    </div>
                  )}
                </div>
              </Button>
            ))}
          </div>
        ) : (
          <div className="text-center py-8">
            <p className="text-muted-foreground mb-4">You don't have any playlists yet</p>
            <p className="text-sm text-muted-foreground">
              Create a playlist first to save animations
            </p>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

// src/components/AddToPlaylistModal.svelte
<script lang="ts">
	import { Plus, Loader2 } from '@lucide/svelte';
	import { auth } from '$lib/auth.svelte';
	import { supabase } from '$lib/supabase';
	import { toast } from '$lib/toast.svelte';
	import { user_playlists } from '$lib/data';
	import type { Playlist } from '$lib/types';

	let { animation_id, title }: { animation_id: string; title: string } = $props();
	const a = auth();
	let open = $state(false);
	let loading = $state(false);
	let busy = $state(false);
	let playlists = $state<Playlist[]>([]);

	async function load() {
		if (!a.user) return;
		loading = true;
		try {
			playlists = await user_playlists(a.user.id);
		} catch (e) {
			toast('error', e instanceof Error ? e.message : 'failed', 'err');
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		if (open) load();
	});

	async function add(id: string) {
		if (!a.user) return;
		busy = true;
		try {
			const { error } = await supabase.from('playlist_items').insert({ playlist_id: id, post_id: animation_id });
			if (error) throw error;
			const p = playlists.find((x) => x.id === id);
			toast('added to playlist!', `"${title}" was added to "${p?.name}"`);
			open = false;
		} catch (e) {
			const msg = e instanceof Error ? e.message : '';
			if (msg.includes('duplicate key value')) toast('already in playlist', 'this animation is already in that playlist', 'err');
			else toast('failed to add to playlist', msg, 'err');
		} finally {
			busy = false;
		}
	}
</script>

{#if a.user}
	<button class="btn-outline-sm" type="button" onclick={() => (open = true)}>
		<Plus class="mr-2 h-4 w-4" /> add to playlist
	</button>
	{#if open}
		<div class="overlay" onclick={() => (open = false)} onkeydown={(e) => e.key === 'Escape' && (open = false)} role="presentation">
			<div class="modal max-w-md" tabindex="-1" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()} role="dialog" aria-modal="true">
				<h2 class="text-lg font-semibold">add to playlist</h2>
				<p class="mb-4 text-sm text-muted-foreground">choose a playlist to add "{title}" to</p>
				{#if loading}
					<div class="flex justify-center py-8"><Loader2 class="h-6 w-6 animate-spin" /></div>
				{:else if playlists.length}
					<div class="max-h-60 space-y-2 overflow-y-auto">
						{#each playlists as p (p.id)}
							<button class="btn-ghost h-auto w-full justify-start p-4" type="button" disabled={busy} onclick={() => add(p.id)}>
								<div class="text-left">
									<div class="font-medium">{p.name}</div>
									{#if p.description}<div class="line-clamp-2 text-sm text-muted-foreground">{p.description}</div>{/if}
								</div>
							</button>
						{/each}
					</div>
				{:else}
					<div class="py-8 text-center text-muted-foreground">
						<p class="mb-2">you don't have any playlists yet</p>
						<p class="text-sm">create a playlist first to save animations</p>
					</div>
				{/if}
			</div>
		</div>
	{/if}
{/if}
