// src/components/CommunityCombobox.svelte
<script lang="ts">
	import { Check, ChevronsUpDown, Plus } from '@lucide/svelte';
	import { search_communities } from '$lib/data';
	import { cn } from '$lib/utils';

	let { value = $bindable(''), disabled = false }: { value?: string; disabled?: boolean } = $props();
	let open = $state(false);
	let term = $state('');
	let communities = $state<{ id: string; name: string; display_name: string }[]>([]);

	$effect(() => {
		search_communities(term).then((d) => (communities = d));
	});

	const selected = $derived(communities.find((c) => c.id === value));
	const label = $derived(
		value === 'none' ? 'no community' : value === 'create-new' ? 'create new community' : selected?.display_name || 'select a community'
	);

	function pick(v: string) {
		value = v;
		open = false;
	}
</script>

<div class="relative">
	<button type="button" class="btn-outline w-full justify-between" onclick={() => (open = !open)} {disabled}>
		{label}
		<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
	</button>
	{#if open}
		<div class="absolute z-20 mt-1 w-full rounded-md border bg-background shadow">
			<input class="field border-0 border-b" placeholder="search communities..." bind:value={term} />
			<div class="max-h-56 overflow-y-auto py-1">
				<button type="button" class="flex w-full items-center px-3 py-2 text-sm hover:bg-accent" onclick={() => pick('none')}>
					<Check class={cn('mr-2 h-4 w-4', value === 'none' ? 'opacity-100' : 'opacity-0')} /> no community
				</button>
				<button type="button" class="flex w-full items-center px-3 py-2 text-sm hover:bg-accent" onclick={() => pick('create-new')}>
					<Check class={cn('mr-2 h-4 w-4', value === 'create-new' ? 'opacity-100' : 'opacity-0')} />
					<Plus class="mr-2 h-4 w-4" /> create new community
				</button>
				{#each communities as c (c.id)}
					<button type="button" class="flex w-full items-center px-3 py-2 text-sm hover:bg-accent" onclick={() => pick(c.id)}>
						<Check class={cn('mr-2 h-4 w-4', value === c.id ? 'opacity-100' : 'opacity-0')} />
						{c.display_name}
					</button>
				{/each}
			</div>
		</div>
	{/if}
</div>

// src/components/CommunityCombobox.tsx

import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { supabase } from '@/integrations/supabase/client'
import { Check, ChevronsUpDown, Plus } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

interface Community {
  id: string
  name: string
  display_name: string
}

interface CommunityComboboxProps {
  value: string
  onValueChange: (value: string) => void
  disabled?: boolean
}

export const CommunityCombobox = ({ value, onValueChange, disabled }: CommunityComboboxProps) => {
  const [open, setOpen] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')

  const { data: communities } = useQuery({
    queryKey: ['communities', searchTerm],
    queryFn: async (): Promise<Community[]> => {
      let query = supabase
        .from('communities')
        .select('id, name, display_name')
        .order('display_name')

      if (searchTerm) {
        query = query.ilike('display_name', `%${searchTerm}%`)
      }

      const { data, error } = await query.limit(50)
      if (error) throw error
      return data || []
    }
  })

  const selectedCommunity = communities?.find(community => community.id === value)

  const getDisplayValue = () => {
    if (value === 'none') return 'No community'
    if (value === 'create-new') return 'Create New Community'
    return selectedCommunity?.display_name || 'Select a community'
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between"
          disabled={disabled}
        >
          {getDisplayValue()}
          <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-full p-0">
        <Command>
          <CommandInput 
            placeholder="Search communities..." 
            value={searchTerm}
            onValueChange={setSearchTerm}
          />
          <CommandList>
            <CommandEmpty>No communities found.</CommandEmpty>
            <CommandGroup>
              <CommandItem
                value="none"
                onSelect={() => {
                  onValueChange('none')
                  setOpen(false)
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === 'none' ? "opacity-100" : "opacity-0"
                  )}
                />
                No community
              </CommandItem>
              <CommandItem
                value="create-new"
                onSelect={() => {
                  onValueChange('create-new')
                  setOpen(false)
                }}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value === 'create-new' ? "opacity-100" : "opacity-0"
                  )}
                />
                <Plus className="mr-2 h-4 w-4" />
                Create New Community
              </CommandItem>
              {communities?.map((community) => (
                <CommandItem
                  key={community.id}
                  value={community.id}
                  onSelect={() => {
                    onValueChange(community.id)
                    setOpen(false)
                  }}
                >
                  <Check
                    className={cn(
                      "mr-2 h-4 w-4",
                      value === community.id ? "opacity-100" : "opacity-0"
                    )}
                  />
                  {community.display_name}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  )
}
