// src/components/DiscoverFeed.svelte
<script lang="ts">
	import { Loader2 } from '@lucide/svelte';
	import { list_animations, list_posts } from '$lib/data';
	import type { Animation, Post } from '$lib/types';
	import AnimationCard from './AnimationCard.svelte';
	import PostCard from './PostCard.svelte';

	let { community_id = undefined as string | undefined } = $props();
	let sort = $state<'new' | 'top'>('new');
	let animations = $state<Animation[]>([]);
	let posts = $state<Post[]>([]);
	let loading = $state(true);
	let err = $state('');

	async function load() {
		loading = true;
		err = '';
		try {
			animations = await list_animations(sort, community_id);
			if (!animations.length) posts = await list_posts(sort, community_id);
			else posts = [];
		} catch (e) {
			err = e instanceof Error ? e.message : 'unknown error';
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		void sort;
		void community_id;
		load();
	});
</script>

<div class="space-y-6">
	<div class="flex space-x-2">
		<button class={sort === 'new' ? 'btn-sm' : 'btn-outline-sm'} type="button" onclick={() => (sort = 'new')}>new</button>
		<button class={sort === 'top' ? 'btn-sm' : 'btn-outline-sm'} type="button" onclick={() => (sort = 'top')}>top</button>
	</div>
	{#if err && !animations.length && !posts.length}
		<div class="py-12 text-center">
			<p class="text-muted-foreground">failed to load content</p>
			<p class="mt-2 text-sm text-muted-foreground">{err}</p>
		</div>
	{:else if loading}
		<div class="py-12 text-center">
			<Loader2 class="mx-auto mb-4 h-8 w-8 animate-spin" />
			<p class="text-muted-foreground">loading content...</p>
		</div>
	{:else if animations.length}
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each animations as animation (animation.id)}
				<AnimationCard {animation} />
			{/each}
		</div>
	{:else if posts.length}
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each posts as post (post.id)}
				<PostCard {post} />
			{/each}
		</div>
	{:else}
		<div class="py-12 text-center">
			<p class="text-muted-foreground">no content found</p>
			<p class="mt-2 text-sm text-muted-foreground">be the first to share your work!</p>
		</div>
	{/if}
</div>

// src/components/DiscoverFeed.tsx
import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { supabase } from '@/integrations/supabase/client'
import { Button } from '@/components/ui/button'
import { PostCard } from './PostCard'
import { Loader2 } from 'lucide-react'

type SortType = 'new' | 'top'

interface Post {
  id: string
  title: string
  thumbnail_url: string | null
  video_url: string | null
  upvote_count: number
  created_at: string
  author: {
    username: string
    avatar_url: string | null
  }
  community: {
    name: string
    display_name: string
  } | null
}

export const DiscoverFeed: React.FC<{ communityId?: string }> = ({ communityId }) => {
  const [sortBy, setSortBy] = useState<SortType>('new')

  const { data: posts, isLoading, error } = useQuery({
    queryKey: ['posts', sortBy, communityId],
    queryFn: async (): Promise<Post[]> => {
      console.log('Fetching posts with sort:', sortBy, 'and communityId:', communityId)
      
      let query = supabase
        .from('posts')
        .select(`
          id,
          title,
          thumbnail_url,
          video_url,
          upvote_count,
          created_at,
          author:users!author_id (
            username,
            avatar_url
          ),
          community:communities (
            name,
            display_name
          )
        `)

      if (communityId) {
        query = query.eq('community_id', communityId)
      }

      // Sort by the selected option
      if (sortBy === 'new') {
        query = query.order('created_at', { ascending: false })
      } else {
        query = query.order('upvote_count', { ascending: false })
      }

      const { data, error } = await query.limit(20)

      if (error) {
        console.error('Error fetching posts:', error)
        throw error
      }

      console.log('Fetched posts:', data)
      return data || []
    }
  })

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="text-muted-foreground">Failed to load animations</p>
        <p className="text-sm text-muted-foreground mt-2">
          {error instanceof Error ? error.message : 'Unknown error'}
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Filter Buttons */}
      <div className="flex space-x-2">
        <Button
          variant={sortBy === 'new' ? 'default' : 'outline'}
          onClick={() => setSortBy('new')}
        >
          New
        </Button>
        <Button
          variant={sortBy === 'top' ? 'default' : 'outline'}
          onClick={() => setSortBy('top')}
        >
          Top
        </Button>
      </div>

      {/* Loading State */}
      {isLoading && (
        <div className="text-center py-12">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4" />
          <p className="text-muted-foreground">Loading animations...</p>
        </div>
      )}

      {/* Posts Grid */}
      {!isLoading && posts && posts.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {posts.map((post) => (
            <PostCard key={post.id} post={post} />
          ))}
        </div>
      )}

      {/* Empty State */}
      {!isLoading && posts && posts.length === 0 && (
        <div className="text-center py-12">
          <p className="text-muted-foreground">No animations found</p>
          <p className="text-sm text-muted-foreground mt-2">
            Be the first to share your work!
          </p>
        </div>
      )}
    </div>
  )
}
