// src/components/FileUploadSection.svelte
<script lang="ts">
	import { Video, Image, X } from '@lucide/svelte';

	let {
		video = $bindable<File | null>(null),
		thumb = $bindable<File | null>(null),
		disabled = false
	}: { video?: File | null; thumb?: File | null; disabled?: boolean } = $props();

	let video_el: HTMLInputElement | undefined = $state();
	let thumb_el: HTMLInputElement | undefined = $state();

	function pick_video(e: Event) {
		const f = (e.target as HTMLInputElement).files?.[0];
		if (f) video = f;
	}
	function pick_thumb(e: Event) {
		const f = (e.target as HTMLInputElement).files?.[0];
		if (f) thumb = f;
	}
</script>

<div class="space-y-2">
	<label class="text-sm font-medium" for="video-file">video file *</label>
	<div class="flex items-center space-x-2">
		<button type="button" class="btn-outline flex-1" onclick={() => video_el?.click()} {disabled}>
			<Video class="mr-2 h-4 w-4" />
			{video ? video.name : 'select video file'}
		</button>
		{#if video}
			<button type="button" class="btn-icon" onclick={() => (video = null)} {disabled}><X class="h-4 w-4" /></button>
		{/if}
	</div>
	<input bind:this={video_el} id="video-file" type="file" accept="video/*" class="hidden" onchange={pick_video} {disabled} />
	<p class="text-xs text-muted-foreground">supported formats: mp4, mov, avi, etc. max size: 50mb</p>
</div>
<div class="space-y-2">
	<label class="text-sm font-medium" for="thumb-file">custom thumbnail (optional)</label>
	<div class="flex items-center space-x-2">
		<button type="button" class="btn-outline flex-1" onclick={() => thumb_el?.click()} {disabled}>
			<Image class="mr-2 h-4 w-4" />
			{thumb ? thumb.name : 'select thumbnail image'}
		</button>
		{#if thumb}
			<button type="button" class="btn-icon" onclick={() => (thumb = null)} {disabled}><X class="h-4 w-4" /></button>
		{/if}
	</div>
	<input bind:this={thumb_el} id="thumb-file" type="file" accept="image/*" class="hidden" onchange={pick_thumb} {disabled} />
	<p class="text-xs text-muted-foreground">if not provided, a thumbnail will be auto-generated from the video. max size: 5mb</p>
</div>

// src/components/FileUploadSection.tsx

import React, { useRef } from 'react'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Video, Image as ImageIcon, X } from 'lucide-react'

interface FileUploadSectionProps {
  videoFile: File | null
  thumbnailFile: File | null
  onVideoChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  onThumbnailChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  onVideoRemove: () => void
  onThumbnailRemove: () => void
  disabled: boolean
}

export const FileUploadSection = ({
  videoFile,
  thumbnailFile,
  onVideoChange,
  onThumbnailChange,
  onVideoRemove,
  onThumbnailRemove,
  disabled
}: FileUploadSectionProps) => {
  const videoInputRef = useRef<HTMLInputElement>(null)
  const thumbnailInputRef = useRef<HTMLInputElement>(null)

  return (
    <>
      <div className="space-y-2">
        <Label htmlFor="video-file">Video File *</Label>
        <div className="flex items-center space-x-2">
          <Button
            type="button"
            variant="outline"
            onClick={() => videoInputRef.current?.click()}
            disabled={disabled}
            className="flex-1"
          >
            <Video className="h-4 w-4 mr-2" />
            {videoFile ? videoFile.name : 'Select Video File'}
          </Button>
          {videoFile && (
            <Button
              type="button"
              variant="ghost"
              size="icon"
              onClick={onVideoRemove}
              disabled={disabled}
            >
              <X className="h-4 w-4" />
            </Button>
          )}
        </div>
        <input
          ref={videoInputRef}
          type="file"
          accept="video/*"
          onChange={onVideoChange}
          className="hidden"
          disabled={disabled}
        />
        <p className="text-xs text-muted-foreground">
          Supported formats: MP4, MOV, AVI, etc. Max size: 50MB
        </p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="thumbnail-file">Custom Thumbnail (Optional)</Label>
        <div className="flex items-center space-x-2">
          <Button
            type="button"
            variant="outline"
            onClick={() => thumbnailInputRef.current?.click()}
            disabled={disabled}
            className="flex-1"
          >
            <ImageIcon className="h-4 w-4 mr-2" />
            {thumbnailFile ? thumbnailFile.name : 'Select Thumbnail Image'}
          </Button>
          {thumbnailFile && (
            <Button
              type="button"
              variant="ghost"
              size="icon"
              onClick={onThumbnailRemove}
              disabled={disabled}
            >
              <X className="h-4 w-4" />
            </Button>
          )}
        </div>
        <input
          ref={thumbnailInputRef}
          type="file"
          accept="image/*"
          onChange={onThumbnailChange}
          className="hidden"
          disabled={disabled}
        />
        <p className="text-xs text-muted-foreground">
          If not provided, a thumbnail will be auto-generated from the video. Max size: 5MB
        </p>
      </div>
    </>
  )
}
