// src/components/auth/SignUpForm.svelte
<script lang="ts">
	import { sign_up, sign_in_google, auth } from '$lib/auth.svelte';
	import { toast } from '$lib/toast.svelte';
	import GoogleIcon from '$components/GoogleIcon.svelte';

	let { on_toggle }: { on_toggle: () => void } = $props();
	const a = auth();
	let email = $state('');
	let password = $state('');
	let username = $state('');
	let confirm = $state('');

	async function submit(e: Event) {
		e.preventDefault();
		if (password !== confirm) {
			toast('error', 'passwords do not match', 'err');
			return;
		}
		if (password.length < 6) {
			toast('error', 'password must be at least 6 characters', 'err');
			return;
		}
		try {
			await sign_up(email, password, username);
		} catch {
			/* toast */
		}
	}
</script>

<div class="space-y-6">
	<button class="btn-outline w-full" type="button" onclick={() => sign_in_google()} disabled={a.loading}>
		<GoogleIcon class="mr-2 h-4 w-4" />
		sign up with google
	</button>
	<div class="relative">
		<div class="absolute inset-0 flex items-center"><span class="w-full border-t"></span></div>
		<div class="relative flex justify-center text-xs uppercase">
			<span class="bg-background px-2 text-muted-foreground">or continue with email</span>
		</div>
	</div>
	<form onsubmit={submit} class="space-y-4">
		<div class="space-y-2">
			<label class="text-sm font-medium" for="username">username</label>
			<input id="username" class="field" type="text" bind:value={username} required disabled={a.loading} minlength="3" maxlength="50" />
		</div>
		<div class="space-y-2">
			<label class="text-sm font-medium" for="email">email</label>
			<input id="email" class="field" type="email" bind:value={email} required disabled={a.loading} />
		</div>
		<div class="space-y-2">
			<label class="text-sm font-medium" for="password">password</label>
			<input id="password" class="field" type="password" bind:value={password} required disabled={a.loading} minlength="6" />
		</div>
		<div class="space-y-2">
			<label class="text-sm font-medium" for="confirm">confirm password</label>
			<input id="confirm" class="field" type="password" bind:value={confirm} required disabled={a.loading} minlength="6" />
		</div>
		<button class="btn w-full" type="submit" disabled={a.loading}>{a.loading ? 'creating account...' : 'sign up'}</button>
	</form>
	<div class="text-center">
		<button type="button" class="text-sm text-primary hover:underline" onclick={on_toggle} disabled={a.loading}>
			already have an account? sign in
		</button>
	</div>
</div>

// src/components/auth/SignUpForm.tsx

import React, { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useAuth } from '@/contexts/AuthContext'
import { GoogleIcon } from '@/components/GoogleIcon'

interface SignUpFormProps {
  onToggleMode: () => void
}

export const SignUpForm: React.FC<SignUpFormProps> = ({ onToggleMode }) => {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [username, setUsername] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const { signUp, loading, signInWithGoogle } = useAuth()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (password !== confirmPassword) {
      alert('Passwords do not match')
      return
    }

    if (password.length < 6) {
      alert('Password must be at least 6 characters')
      return
    }

    try {
      await signUp(email, password, username)
    } catch (error) {
      // Error is handled in the auth context
    }
  }

  return (
    <div className="space-y-6">
      <Button variant="outline" className="w-full" onClick={() => signInWithGoogle()} disabled={loading}>
        <GoogleIcon className="mr-2 h-4 w-4" />
        Sign Up with Google
      </Button>

      <div className="relative">
        <div className="absolute inset-0 flex items-center">
          <span className="w-full border-t" />
        </div>
        <div className="relative flex justify-center text-xs uppercase">
          <span className="bg-background px-2 text-muted-foreground">
            Or continue with email
          </span>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="username">Username</Label>
          <Input
            id="username"
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            disabled={loading}
            minLength={3}
            maxLength={50}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input
            id="email"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            disabled={loading}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            disabled={loading}
            minLength={6}
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="confirmPassword">Confirm Password</Label>
          <Input
            id="confirmPassword"
            type="password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
            disabled={loading}
            minLength={6}
          />
        </div>

        <Button type="submit" className="w-full" disabled={loading}>
          {loading ? 'Creating account...' : 'Sign Up'}
        </Button>
      </form>

      <div className="text-center">
        <button
          type="button"
          onClick={onToggleMode}
          className="text-sm text-primary hover:underline"
          disabled={loading}
        >
          Already have an account? Sign in
        </button>
      </div>
    </div>
  )
}
